### ISSUE TITLE
Watched files not uploading.  this.upload is not a function

### ISSUE THREAD

**Issue by aaroncrawford** [njpanderson/push#69]
- Push version: `0.8.2`
 - VS Code version: `1.41.1`
 - Have you disabled all other extensions and can replicate: [Yes]

I've just begun getting the following error after setting up a watch on a CSS file.  After editing a SCSS file and having this CSS file change via webpack, the following is thrown.  I have disabled every other extension and do not receive this error, however the file still does not upload.  I've tried various conditions on the file such as truncating it, then having webpack push over a little CSS to it so that it changes - Push doesn't respond at all to the change.  If I manually right click on the CSS file and select upload, everything works as normal so I don't believe it's my settings.  After the file changes, the Push console is blank - no errors, notices or anything of the sort.

I have included a GIF of the behavior here as well :

https://d.pr/i/Sh0cJF

Thanks for your help.

`[2020-01-10 15:37:58.396] [renderer1] [error] this.upload is not a function: TypeError: this.upload is not a function
    at T.onWatchChange (/Users/aaron/.vscode/extensions/njp-anderson.push-0.8.2/src/Push.js:822:9)
    at s._watcherChangeApplied (/Users/aaron/.vscode/extensions/njp-anderson.push-0.8.2/src/Watch/ListItem.js:50:7)
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:893)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:568:380
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:893)
    at t.ExtHostFileSystemEventService.$onFileEvent (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:569:698)
    at p._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:663:275)
    at p._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:662:971)
    at p._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:661:639)
    at p._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:660:468)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:658:691
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:893)
    at _.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:189:274)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:820:285
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:893)
    at _.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:189:274)
    at t.PersistentProtocol._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:193:629)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:190:824
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:893)
    at p.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:186:737)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:186:89
    at Socket.t (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:195:68)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)`

**Comment by DaveWoody** [comment]
Got the same issue. Currently uploading the files manually again.

**Comment by darklord1807** [comment]
same issue. any fix?

**Comment by njpanderson** [comment]
Oh my, apologies guys. This issue landed in my Junk mail!

Will look at it right now.

**Comment by njpanderson** [comment]
Fixed in 0.8.21. Thanks for reporting.
